services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: ha-nanit-dev
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./ha-config:/config
      - ../custom_components:/config/custom_components:ro
    environment:
      - TZ=Europe/Oslo
