name: Release Beta

on:
  release:
    types: [published]

jobs:
  publish-beta:
    name: Publish Beta to PyPI
    if: github.event.release.prerelease == true
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/aionanit/
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          ref: ${{ github.event.release.tag_name }}

      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: "3.12"

      - name: Install build
        run: pip install build

      - name: Build package
        working-directory: packages/aionanit
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b
        with:
          packages-dir: packages/aionanit/dist/
